### ISSUE TITLE
hud disappears after abs rad fight

### ISSUE THREAD

**Issue by yuval52** [ygsbzr/HollowKnight.CustomPantheon#3]
when abs rad is put not at the end of a pantheon, the hud disappears after the end of the fight

**Comment by ygsbzr** [comment]
it's a pantheon bug, you can install another mod called hudInChecker to deal with it,and  PV also can cause this,but this mod is not on scarab,so I will fix this.

**Comment by yuval52** [comment]
i have seen you updated the mod, is this it? i tried it again and the problem continues

**Comment by ygsbzr** [comment]
Oh ,sorry,I upload the wrong file,will fix
